### PR TITLE
Fix deploy task and helm3 error (#13)

### LINKED ISSUE #13: gradle helmDeploy explanation
Well, before I issue a PR (if that will be needed at all), I have a question. 

How do I configure the plugin so that `gradle helmDeploy` works? In case I am missing the obvious here... thank you

### PR DESCRIPTION
**Pull request by jekkel**
fixes #13 
also add initial testing

### CODE REVIEW

File: src/main/java/com/kiwigrid/k8s/helm/tasks/RepoSyncTask.java [hunk 1]
```diff
@@ -152,7 +160,7 @@ private void addRepo(HelmRepository repo) {
 			return;
 		}
 		if (repo.isAuthenticated()) {
-			helmExec(getProject(), this,
+			helmExecSuccess(getProject(), this,
```
Comment (wind57) [inline src/main/java/com/kiwigrid/k8s/helm/tasks/RepoSyncTask.java:163]: perfect. this is exactly what I did in one of my PRs, I guess I could close that one then?

**Comment by wind57** [comment]
can I ask if yo tested this PR against any real helm repos? like artifactory or anything else? You are supposed to pass a multi-part request to those repos, and I don't see where that might happen... thank you.

File: src/main/java/com/kiwigrid/k8s/helm/tasks/HelmDeployTask.java [hunk 2]
```diff
@@ -46,16 +44,6 @@ public void deploy() throws IOException {
...
-	public File getChartFolder() {
-		return chartFolder;
-	}
-
-	public HelmDeployTask setChartFolder(File chartFolder) {
-		this.chartFolder = chartFolder;
-		return this;
-	}
-
 	@Input
```
Comment (wind57) [inline src/main/java/com/kiwigrid/k8s/helm/tasks/HelmDeployTask.java:47]: `target` is not an input anymore, so I guess you can remove that annotation. Also, you could probably remove the `getter` also

**Comment by jekkel** [comment]
> can I ask if you tested this PR against any real helm repos? like artifactory or anything else? You are supposed to pass a multi-part request to those repos, and I don't see where that might happen... thank you.

I read the docs and we've been using Chartmuseum for a while successfully. But both [artifactory docs](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-Example-DeployinganArtifact) and [chartmuseum docs](https://chartmuseum.com/docs/#uploading-a-chart-package) indicate a plain PUT/POST should be ok (note the `-T` option of curl in contrast to `-F`).

That being said, I'd be ok with an extension which allows the user to specify that a multipart upload should be used instead. That should be part of the "mini dsl for uploads" and properly tested.

File: src/main/java/com/kiwigrid/k8s/helm/tasks/HelmDeployTask.java (hunk 2 above)
Comment (jekkel) [reply src/main/java/com/kiwigrid/k8s/helm/tasks/HelmDeployTask.java:45]: I don't get it... As far as I can tell it still is an input, isn't it?

File: src/main/java/com/kiwigrid/k8s/helm/tasks/RepoSyncTask.java (hunk 1 above)
Comment (jekkel) [reply src/main/java/com/kiwigrid/k8s/helm/tasks/RepoSyncTask.java:161]: maybe not because you added multipart there. I don't intend to add multipart in this PR

File: src/main/java/com/kiwigrid/k8s/helm/tasks/HelmDeployTask.java (hunk 2 above)
Comment (wind57) [reply src/main/java/com/kiwigrid/k8s/helm/tasks/HelmDeployTask.java:45]: sorry, you might be right. please ignore

**Comment by wind57** [comment]
> > can I ask if you tested this PR against any real helm repos? like artifactory or anything else? You are supposed to pass a multi-part request to those repos, and I don't see where that might happen... thank you.
> 
> I read the docs and we've been using Chartmuseum for a while successfully. But both [artifactory docs](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-Example-DeployinganArtifact) and [chartmuseum docs](https://chartmuseum.com/docs/#uploading-a-chart-package) indicate a plain PUT/POST should be ok (note the `-T` option of curl in contrast to `-F`).
> 
> That being said, I'd be ok with an extension which allows the user to specify that a multipart upload should be used instead. That should be part of the "mini dsl for uploads" and properly tested.

once you merge these PRs (and may be the ones I put up if you have time to review), I'll retest this with out helm repo. We use a custom atlas one (not sure if this is known) and that requires a multi-part; but I will investigate if it supports more.

File: src/main/java/com/kiwigrid/k8s/helm/tasks/RepoSyncTask.java (hunk 1 above)
Comment (wind57) [reply src/main/java/com/kiwigrid/k8s/helm/tasks/RepoSyncTask.java:161]: no no, I mean [this one](https://github.com/kiwigrid/helm-gradle-plugin/pull/16), not the one with multi-part, which we can safely ignore for now

Comment (jekkel) [reply src/main/java/com/kiwigrid/k8s/helm/tasks/RepoSyncTask.java:161]: oh I see, yes, that one can be closed. I also incorporated your proposal of renaming the repo sync task. :+1:
